# ---
# title: 3mm Stack-of-Spiral fMRI
# author: Pierre-Antoine Comby, Alexandre Vignaud, Philippe Ciuciu
# description: This is the configuration used for the scenario 2 of the SNAKE Paper
# ---

defaults:
  - base_config
  - handlers:
    - activation-block
  - sampler:
    - stack-of-spiral
  - reconstructors:
      # - adjoint
      - sequential
      - sequential-pnp
  - _self_

cache_dir: ${oc.env:PWD}/cache
result_dir: results/scenario2
filename:  ${cache_dir}/pnp_${engine.model}_${engine.snr}_${sampler.stack-of-spiral.constant}_${sampler.stack-of-spiral.accelz}.mrd

sim_conf:
  max_sim_time: 300
  seq: {TR: 50, TE: 25,  FA: 12}
  hardware:
    n_coils: 8
    field: 7
    dwell_time_ms: 0.001
  fov:
    size: [192,192,144]
    angles: [-5,0,0]
    res_mm: [3,3,3]
    offset: [-90,-110,-35]

phantom:
  name: brainweb
  sub_id: 4
  tissue_file: "tissue_7T"

handlers:
  activation-block:
    event_name: block_on
    block_on: 20 # seconds
    block_off: 20 #seconds
    duration: 300 # seconds
    delta_r2s: 1000 # millisecond^-1
    atlas: null

sampler:
  stack-of-spiral:
    acsz: 0.1
    accelz: 4
    nb_revolutions: 12
    constant: true
    spiral_name: "archimedes"
    orderz: "top-down"

engine:
  n_jobs: 5
  chunk_size: 180
  model: "T2s"
  snr: 1000
  nufft_backend: "stacked-cufinufft"
reconstructors:
  # adjoint:
  #   nufft_backend: "stacked-gpunufft"
  #   density_compensation: "pipe"
  sequential-pnp:
    model_weights: ${oc.env:PWD}/weights/drunet_3d_0303.pth
    nufft_backend: stacked-cufinufft
    density_compensation: null
    device: cuda
    x_init: pinv
    dpir_params:
      xi: 0.97
      stepsize: 13
      sigma: 0.004
    max_iter_per_frame: 20
    optimizer: hqs-f1

  sequential:
    nufft_backend: "stacked-cufinufft"
    density_compensation: false
    restart_strategy: COLD
    max_iter_per_frame: 50
    wavelet: "sym4"





hydra:
  job:
    chdir: true

  run:
    dir: ${result_dir}/outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/multirun/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

  callbacks:
    # gather_files:
    #   _target_: hydra_callbacks.MultiRunGatherer
    #   aggregator:
    #     _partial_: true
    #     _target_: snkf.cli.utils.aggregate_results

    log_job:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback
    latest_run:
      _target_: hydra_callbacks.LatestRunLink
      run_base_dir:  ${result_dir}/outputs
      multirun_base_dir:  ${result_dir}/multirun
